# Generated by Django 5.2.8 on 2025-11-24 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cajero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='cajero',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='cuentaporcobrar',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='condicionproducto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='cuentaporcobrar',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='venta',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='vendedor',
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Prestamo',
        ),
        migrations.DeleteModel(
            name='CondicionProducto',
        ),
        migrations.DeleteModel(
            name='CuentaPorCobrar',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
