# Generated by Django 5.2.8 on 2025-11-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
