# Generated by Django 5.2.8 on 2025-11-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_administrador', '0002_alter_usuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
