# Generated by Django 5.2.8 on 2025-12-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_administrador', '0003_alter_cliente_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='firma',
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(default='Activo', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento_identidad',
            field=models.CharField(max_length=50),
        ),
    ]
